name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [released]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: | 
        dotnet build --configuration Release --no-restore
        dotnet pack -c Release RangeQueryDotNet.AspNetCore/RangeQueryDotNet.AspNetCore.csproj  --no-restore --include-symbols --include-source -p:SymbolPackageFormat=snupkg -p:PackageVersion=1.0.$GITHUB_RUN_ID 
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish to NuGet
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet nuget push RangeQueryDotNet.AspNetCore/**/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate 